### ISSUE TITLE
Question: Does this client API support Notary and Mirror authentication?

### ISSUE THREAD

**Issue by sean-scott-lr** [kolide/updater#45]
`Notary server optionally supports authentication from clients using JWT tokens. This requires an authorization server that manages access controls, and a cert bundle from this authorization server containing the public key it uses to sign tokens.
If token authentication is enabled on Notary server, then any connecting client that does not have a token will be redirected to the authorization server.
Please see the docs for Docker Registry v2 authentication for more information.`

**Comment by directionless** [comment]
No. That's not something this library suppors.
